version: '3'
services:
  server:
    image: ghcr.io/thehangar/leader-board:1.0
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .db.env

